site_name: Cruky

theme:
  name: material
  palette:
    - scheme: slate
      primary: red
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: red
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

repo_name: seifalmotaz/cruky
repo_url: https://github.com/seifalmotaz/cruky

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Intro: index.md
