site_name: Cruky

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

repo_name: seifalmotaz/cruky
repo_url: https://github.com/seifalmotaz/cruky

markdown_extensions:
  - tables
  - meta
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - Intro: index.md
  - Tutorial:
    - tutorial/01-Appmatrial.md
    - tutorial/02-InApp.md
    - tutorial/03-ServerApp.md
    - tutorial/04-Route Handlers.md
    - tutorial/05-Path Params.md
    - tutorial/06- Request Body.md
    - tutorial/07-Schema Validator.md
    - tutorial/08-Route Handlers Types.md
    - tutorial/09-WebSockets.md
    - tutorial/10-Isolates.md
  - API reference: "https://pub.dev/documentation/cruky/latest/cruky/cruky-library.html"
  - Roadmap: roadmap.md
  - Release Notes: releasenotes.md
