name: cruky
description: cruky is server-side library to create API with modern and fast performance.
version: 0.5.0
repository: https://github.com/seifalmotaz/cruky

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  mime: ^1.0.1
  watcher: ^1.0.1
  args: ^2.3.0
  logging: ^1.0.2
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
