name: cruky
description: cruky is server-side library to create API with modern and fast performance.
version: 0.9.0
homepage: https://github.com/seifalmotaz/cruky
repository: https://github.com/seifalmotaz/cruky
documentation: https://github.com/seifalmotaz/cruky/wiki

environment:
  sdk: ">=2.16.1 <3.0.0"

executables:
  cruky: cruky

dependencies:
  mime: ^1.0.1
  path: ^1.8.1
  # for the hotreload
  watcher: ^1.0.1
  vm_service: ^8.2.2
  # for cli
  args: ^2.3.0
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
