name: cruky
description: A starting point for Dart libraries or applications.
version: 0.0.2
repository: https://github.com/seifalmotaz/cruky

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  mime: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
