name: benchmarks
description: cruky is server-side library to create API with modern and fast performance.
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dio: ^4.0.6
  cruky:
    path: ../

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
